### ISSUE TITLE
pkg.go.dev does not display documentation

### ISSUE THREAD

**Issue by jba** [smasher164/mem#3]
https://pkg.go.dev/github.com/smasher164/mem is not displaying documentation due to license restrictions. The reason is because this package uses the BSD-0-Clause, which is not in our listed of accepted licenses, as listed on our [license policy page](https://pkg.go.dev/license-policy).

If you would like pkg.go.dev/github.com/smasher164/mem to display documentation and other restricted data on pkg.go.dev, please:
- Update the license content according to to the policy at pkg.go.dev/license-policy
- Fetch the updated package from proxy.golang.org, following the instructions at go.dev/about

**Comment by smasher164** [comment]
This seems to be resolved with the latest version of pkg.go.dev. Thanks for your help!
